#ci pipeline start, code checkout, test, build, scan, publish
name: action test
#on: [push,workflow_dispatch]
#jobs:  
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: set java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'

      - name: mavan test
        run: mvn test

      - name: Build with Maven
        run: mvn clean install
 # publishing package to github packages  
      - name: Publish package
        run: mvn --batch-mode -X deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHP_TOKEN }}
